---
# tasks file for awx-test
- name: Get home var
  shell: echo $HOME
  register: home_res

- debug:
    var: home_res.stdout

- name: Get hostname
  shell: hostname
  register: hostname_res

- debug:
    var: hostname_res.stdout